### ISSUE TITLE
Error when exclude.area is set to TRUE

### ISSUE THREAD

**Issue by pjbouchet** [gdauby/ConR#1]
I am getting the following error when running the EOO.computing function and setting exclude.area = TRUE: 
in UseMethod("set_units") : 
  no applicable method for 'set_units' applied to an object of class "character"

This applies to both convex hull and alpha-shape calculations. It would appear that the error originates from the .crop.poly function.
Any thoughts on how to fix this? Many thanks.

**Comment by gdauby** [comment]
Do you still have the error when using the latest version?
```
install.packages("devtools")
devtools::install_github("gdauby/ConR")
```
If yes, could you provide me a reproducible dataset?

**Comment by pjbouchet** [comment]
Yes, still getting the same error.

Here is an example dataset:

structure(c(-16.5241, -18.04249, -17.9915, -16.48294, -18.016307, 
-17.99045, -18.02805, -17.98695, -17.98898, -15.25229, -17.98624, 
-18.00101, -14.47332, -18.023, -18.0210100005557, -18.001, -18.007503, 
-18.01239, -18.0493800005565, -15.440235, -13.72770271, -17.9863000005548, 
-17.9900000005549, -16.17719786, -18.0328100005561, -17.978833, 
-16.4792000005139, -16.59973, -17.986, -18.0352700005561, -17.992510000555, 
-17.995350000555, -17.990832, -18.0195, -18.0277800005559, -16.58645, 
-17.977067, -18.008889, -16.6732100005192, -17.9820000005547, 
-18.071383, -17.98479, -17.9881600005549, -15.40352, -18.00879, 
-17.989631, -16.63822, -18.10436, -14.987775, -17.992430000555, 
-17.986267, -18.031650000556, -17.984, -17.98971, -18.067, -18.11335, 
-17.977067, -17.9894700005549, -18.00509, -16.1306500005042, 
-17.9910000005549, -17.9898200005549, -15.621767, -16.57291, 
-18.050499, -15.0379, -16.5971500005171, -17.983, -18.00053, 
-15.47216, -17.994430000555, -16.1356000005043, -18.00831, -18.1174500005583, 
-17.996, -17.9900700005549, -17.989832, -18.02101, -17.977067, 
-18.12518, -17.98873, -15.13856, -16.61731, -17.9814600005547, 
-17.99215, -16.64991, -17.990721, -17.9883800005549, -18.000778, 
-17.998, -17.991581, -18.06134, -18.021168, -18.038948, -18.001675, 
-16.4986100005144, -17.9906300005549, -17.983, -16.573, -17.9899900005549, 
-18.13844, -17.992451, -17.989083, -18.02799, -18.0094900005554, 
-17.994313, -18.03281, -18.03175, -18.1322100005587, -17.9879700005548, 
-18.00775, -16.59883, -16.49529, -17.993, -16.65549, -18.03913, 
-18.0086500005554, -18.018, -17.9875, -18.02728, -18.001258, 
-18.09804, -18.04027, -18.008, -16.5045300005146, -17.999583, 
-18.033545, -17.9894300005549, -17.992916670555, -16.50803, -17.9879600005548, 
-18.03417, -18.007206, -18.02893, -17.974, -18.02154, -16.47033, 
-18.0230800005558, -16.1358000005043, -17.99183, -17.991939, 
-15.0055, -17.9784, -17.977067, -17.99324, -16.33559621, -18.02163, 
-18.0284100005559, -18.02778, -18.0044400005553, 125.37442, 122.35765, 
123.00186, 122.344233, 122.25939, 123.0436, 123.02699, 122.382, 
122.325855, 122.27633, 122.337, 124.8791667, 122.34743, 122.304693, 
122.32622, 125.0655833, 123.00979, 122.33316, 122.30513333, 122.349436, 
122.31467, 123.64579, 122.35788, 122.299586, 122.319624, 122.30714, 
122.33494, 122.35386, 123.854384, 123.59189, 122.27733, 124.389699, 
122.28521, 123.00134, 122.300767, 122.348618, 124.5820014, 122.303, 
122.26265, 123.00603, 122.29617, 122.344233, 122.32682, 122.35765, 
122.344233, 122.32287, 122.358, 122.353, 123.721866, 123.58738, 
122.32291, 122.33659, 122.344233, 122.36096, 122.32915, 123.00507, 
122.344233, 123.03374, 122.29216, 122.283, 123.01963, 122.33295, 
122.349557, 122.349304, 128.19423, 122.30531, 122.34384, 122.305192, 
122.27157, 122.312838737, 123.00384, 122.2589, 123.01086, 123.01619, 
122.24459, 122.29216, 122.343222, 123.02211, 122.337, 123.04701, 
122.364, 122.29899, 122.344233, 122.24764, 124.8462972, 122.340706, 
126.9672, 122.25861, 122.32384, 122.301, 122.25735, 123.60532, 
122.244487, 123.61702, 122.30746, 122.36922, 122.36096, 122.33468, 
122.34899, 122.313017, 122.344233, 125.117796166667, 125.080105, 
122.283, 122.344233, 122.29488, 123.00012, 122.3271, 122.359179, 
122.24974, 122.34848, 122.31467, 122.3418, 124.583186833333, 
122.34985, 122.31205, 122.267, 124.89218, 122.28513, 122.32974, 
122.28641, 122.32291, 122.36311, 123.02429, 122.284, 122.268, 
122.338, 124.66826, 122.36743, 122.313017, 122.279442, 122.2589, 
122.3418, 123.02458, 122.344233, 125.0759038, 122.37264, 122.293, 
122.3522, 122.26392, 122.337, 122.25191, 122.382, 122.2954, 122.307377, 
125.554722, 122.5560254, 122.24581, 123.00017, 122.26976), .Dim = c(150L, 
2L), .Dimnames = list(NULL, c("y", "x")))

**Comment by gdauby** [comment]
Using your dataset (test is your dataset):
`
library(ConR)
data(land)
EOO.computing(test, exclude.area = T, country_map = land)
`
It's working for me.
Are you using a different shapefile for country_map?

**Comment by pjbouchet** [comment]
I was - but it's working now, after rebooting R completely. Thanks and apologies for this.

**Comment by gdauby** [comment]
No problem.
Glad to know it's working
