### ISSUE TITLE
Precision issue in EOO.computing

### ISSUE THREAD

**Issue by LimaRAF** [gdauby/ConR#17]
Dear @gdauby 

Function EOO.computing is returning 0 for a non-zero EOO (i.e. 0.05316133 km2), due to rounding issues. Digging a little bit, I found that the issue comes from the internal function '.EOO.comp' within 'EOO.computing' (at least for the case of the example below):

Here you are the test data and the codes as they are today:
```
XY <- cbind.data.frame(ddlat = c("-19.34361", "-19.34611"," -19.34833","-19.34819"),
                      ddlon = c("-40.55222", "-40.54972", "-40.55111", "-40.55097"),
                      stringsAsFactors = FALSE)

p1 <- ConR:::.Convex.Hull.Poly(cbind(XY[, 2], XY[, 1]))

EOO <- round(suppressWarnings(geosphere::areaPolygon(p1)) / 1000000, 0)

EOO
```
I suggest the following change in the code, in which rounding depends on the value of EOO itself. If EOO is below 30,000 km2 (IUCN threshold to assess LC species automatically), EOO is given with progressively more decimal digits:

```
p1 <- ConR:::.Convex.Hull.Poly(cbind(XY[, 2], XY[, 1]))

EOO <- suppressWarnings(geosphere::areaPolygon(p1)) / 1000000

digits <- c(6,5,4,3,2,1,0)[findInterval(EOO, c(0, 0.0001, 0.01, 0.1, 1, 10, 30000, Inf))]

EOO <- round(EOO, digits)

EOO

```

Not sure if it is the most elegant/efficient solution, but it does the trick. If you accept it, it would be necessary to check the rest of the function and do the same change inside all the other ifs (e.g. no. of occurrences < 3).

**Comment by gdauby** [comment]
Sounds good to me. I'll make the change.

**Comment by gdauby** [comment]
81df151bd14e1c3289a2cd16e8a8f02d12188994
