### ISSUE TITLE
Error in EOO.computing using "alpha.hull"

### ISSUE THREAD

**Issue by LimaRAF** [gdauby/ConR#18]
Dear @gdauby 

I am getting the following error while running function EOO.computing with method "alpha.hull" and exclude.area = TRUE (I don't get the error with exclude.area = FALSE):
```
"Error in { : 
  task 34 failed - "Evaluation error: TopologyException: Input geom 1 is invalid: Self-intersection at or near point -75.493982248741972 -10.500886007865429 at -75.493982248741972 -10.500886007865429."
```

The function start to calculate the EOO for species (the progress bar appears goes until 100%) and then the error appears. As a remark, I did the gBuffer(neotrop.simp, width = 0) before plugging it in (neotrop.simp = country.map). Maybe this is something related with projections?

Thanks!

Function call:
```
EOO.alpha <- EOO.computing(MyData, 
                                  export_shp = FALSE,
                                  method.range =  "alpha.hull", alpha = 2, 
                                  exclude.area = TRUE, country_map = neotrop.simp, 
                                  write_shp = FALSE, 
                                  write_results=FALSE, file.name = "EOO.alpha", 
                                  parallel = TRUE, NbeCores = 6) 
```

**Comment by gdauby** [comment]
Dear @LimaRAF 
I'll check it.
The 
`gBuffer(neotrop.simp, width = 0) `
is already implemented inside the function so this is not the issue.
I corrected as sf function dependency not called for exclude.area = TRUE so maybe it was that.

**Comment by LimaRAF** [comment]
@gdauby  I am checking here as if it works using gSimplify(x, topologyPreserve = TRUE) to generate the simplified polygons I am using to crop EOO. I was using topologyPreserve = FALSE before and this may have benn the origin of the problem. Will let you know asap.

**Comment by LimaRAF** [comment]
Me again @gdauby . Just tried with a different shape (topologyPreserve = TRUE) and got the same error at the same stage, after the progress bar finished.

**Comment by gdauby** [comment]
This is apparently not related to user-defined country_map as the default one produces the same error.

Computing alpha hull excluding areas does not produce error NOT in parallel

`## Excluding areas, not in parallel, alpha hull
## working fine
EOO.alpha <- EOO.computing(oc.data_subset, 
                           method.range =  "alpha.hull", alpha = 2, 
                           exclude.area = TRUE,
                           parallel = FALSE, NbeCores = 2)` 

Computing alpha hull in parallel but NOT excluding areas does not produce error

`## No excluding areas, in parallel, alpha hull
### working fine
EOO.alpha <- EOO.computing(oc.data_subset, 
                           method.range =  "alpha.hull", alpha = 2, 
                           exclude.area = FALSE,
                           parallel = TRUE, NbeCores = 2)`


Computing alpha hull in parallel excluding areas produces and ERROR

```
TopologyException: Input geom 0 is invalid: Nested shells
at or near point

```

`EOO.alpha <- EOO.computing(oc.data_subset, 
                           method.range =  "alpha.hull", alpha = 2, 
                           exclude.area = TRUE,
                           parallel = TRUE, NbeCores = 2)`

I did several code modifications using `sf::st_make_valid` but I could not fix it. It is very strange that it appears only when running in parallel. Besides, this seems to appear randomly, it is therefore not yet possible to identify the data that lead to such error (and impossible to give a reproducible example).

**Comment by gdauby** [comment]
Given unpredictability of the error and impossibility to provide reproducible example, I suggest to add a warning when jointly use alpha.hull option in parallel.
Far to be optimal but do not see other solution.

**Comment by LimaRAF** [comment]
@gdauby 
It turned out it was much more complicated than what I expected. I agree that a warning should be added to inform users of possible problems. I have not tested the function from your last commit, but I think that the more important would be to return the warning only for the problematic cases/taxa and return the cropped alpha.hull for all other. Maybe add a try() or tryCatch() to recognize the error and avoid the function to crash when it appears. Not sure if you already did it. Let me know if I can do something to help here.

**Comment by gdauby** [comment]
@LimaRAF 
Adding a try() / tryCatch() sounds like the think to do. Haven't done it yet.

**Comment by gdauby** [comment]
@LimaRAF 
The bug is apparently fixed with the last commit.
Should be checked by installing the devel version
`devtools::install_github("gdauby/ConR@devel")`

**Comment by LimaRAF** [comment]
@gdauby I installed the last version of the package from the devel branch. Now I am getting a similar error using the function `EOO.sensitivity` using the "convex.hull"! Since `EOO.sensitivity` also uses `EOO.computing` I am assuming that this is the same issue. I tried to run it with parallel = FALSE overnight, but I finally got the same error message.

Let me know if you want any help with this.

Found this topic that may help:
https://gis.stackexchange.com/questions/223252/how-to-overcome-invalid-input-geom-and-self-intersection-when-intersecting-shape

**Comment by LimaRAF** [comment]
@gdauby I am trying to find the bug here. It seems that it trace backs to function `Convex.Hull.Poly` but I am not sure yet. Or it is related to the new `mode` and `proj_type` arguments which are not declared in all functions (less proable).

**Comment by gdauby** [comment]
@LimaRAF 
all spatial EOO objects and operations are now conducted as sf objects and sf functions, except for alpha.hull.
Let see and test.

**Comment by gdauby** [comment]
@LimaRAF 
I devised a reproducible example to test EOO functions. I suggest we stick on this.

Below successful tests so far.

Could u test the same?

```
set.seed(3)
nbe_occ <- sample(seq(3, 100, 1), 500, replace = TRUE) ### 500 species with number of occurrences sampled between 3 and 100
ddlat <- lapply(nbe_occ, function(x) sample(seq(-10, 15, 0.1), x))
ddlon <- lapply(nbe_occ, function(x) sample(seq(7, 25, 0.1), x))
names(ddlon) <- names(ddlat) <- paste0("tax", seq(1,length(ddlat), 1))
ddlat <- lapply(seq_along(ddlat), function(i) data.frame(ddlat =  ddlat[[i]]))
ddlon <- lapply(seq_along(ddlon), function(i) data.frame(ddlon =  ddlon[[i]], taxa = names(ddlon)[i]))
test_data <- 
  data.frame(ddlat = do.call('rbind', ddlat), ddlon = do.call('rbind', ddlon))
head(test_data)
dim(test_data)

# utilisateur     système      écoulé 
# 214.70        0.52      218.06
system.time(
  EOO <- EOO.computing(test_data)
)

# utilisateur     système      écoulé 
# 202.79        0.66      204.09
system.time(
  EOO <- EOO.computing(test_data, mode = "planar")
)

# utilisateur     système      écoulé 
# 0.52        0.08      113.87
system.time(
  EOO <- EOO.computing(test_data, parallel = TRUE, NbeCores = 2)
)

# utilisateur     système      écoulé 
# 0.66        0.02      106.48
system.time(
  EOO <- EOO.computing(test_data, parallel = TRUE, mode = "planar", NbeCores = 2)
)

# utilisateur     système      écoulé 
# 0.57        0.06       73.56 
system.time(
  EOO <- EOO.computing(test_data, parallel = TRUE, NbeCores = 4)
)


# utilisateur     système      écoulé 
# 231.82        0.64      233.53
system.time(
  EOO <- EOO.computing(test_data, exclude.area = T)
)

# utilisateur     système      écoulé 
# 228.22        1.13      230.22 
system.time(
  EOO <- EOO.computing(test_data, method.range = "alpha.hull")
)

# utilisateur     système      écoulé 
# 0.64        0.13      115.88
system.time(
  EOO <- EOO.computing(test_data, parallel = TRUE, NbeCores = 2, method.range = "alpha.hull")
)


# utilisateur     système      écoulé 
# 237.99        1.31      240.43 
system.time(
  EOO <- EOO.computing(test_data, method.range = "alpha.hull", exclude.area = T)
)

# utilisateur     système      écoulé 
# 0.58        0.06      118.93
system.time(
  EOO <- EOO.computing(test_data, parallel = TRUE, NbeCores = 2, method.range = "alpha.hull", exclude.area = T)
)
```
