### ISSUE TITLE
Saving EOO in ConR::EOO.computing

### ISSUE THREAD

**Issue by LimaRAF** [gdauby/ConR#19]
Dear @gdauby,

I am running the function EOO.computing with the option to save the maps of species EOO (write_shp = TRUE). Some proposals that may help to improve a more advanced use of the function:

1- for my dataset (~ 5100 species, ~500,000 occurrences), it took 2.5 minutes to get the EOO for each species (i.e. to progress bar reach 100%), which is great! However, it took on average about 1 minute to save 25-35 species, so it would take about 50 min to 1 hour to save all shapefiles. Maybe including the saving inside a foreach loop? And maybe test if raster::shapefile can speed up the process?  
2- I recognize that ESRI Shapefile is the most standard format for saving polygons. But it would be nice (and maybe easy to implement) an argument that the user could chose the output format of the object (i.e. 'esri', 'sp' and 'sf')? Default could be 'esri', so the user would need to actively choose other formats.
3- In the same line, maybe add an argument with the name/path of the folder to save all maps? The default could still be "/shapesIUCN", but it may be nice to separate maps in different folders if we want to compare EOO using different subsets of the occurrences (i.e. coordinate precision, taxonomic confidence)

**Comment by gdauby** [comment]
Dear @LimaRAF 
Sounds totally relevant...

**Comment by gdauby** [comment]
@LimaRAF 
Export of shp from EOO.computing is now a Simple feature collection containing all taxa.

Also, a new argument allow changing the driver 
`driver_shp`
by default`
driver_shp = "ESRI Shapefile"`

Much faster at first sight and the advantage to have everything in one shapefile
