### ISSUE TITLE
Bug in AOH.estimation

### ISSUE THREAD

**Issue by pvictor** [gdauby/ConR#31]
Hello Gilles,

Ici il y a un argument `wkt = T` : 

https://github.com/gdauby/ConR/blob/09f07727b410aa914b49ee39a9910019b3bc4450/R/AOH.estimation.R#L152

Alors qu'ici il n'y en a pas : https://github.com/gdauby/ConR/blob/09f07727b410aa914b49ee39a9910019b3bc4450/R/proj_crs.R#L30

Victor

**Comment by gdauby** [comment]
Hello
c'est corrigé.

**Comment by pvictor** [comment]
Merci!
