### ISSUE TITLE
Add elevation clipping

### ISSUE THREAD

**Issue by Erythroxylum** [gdauby/ConR#38]
Suggestion here to add the functionality of clipping EOO and AOO by the elevational range of the species as estimated from occurrence points. This would be especially useful for refining the distributions of montane taxa.
Thank you for this great package!
-Dawson

**Comment by Erythroxylum** [comment]
Hello again. I looked at the AOH.estimation() function but ended up achieving this with the country_map argument in the EOO.estimation; worked just fine after doing all the work to generate a clamped sf for each species. Using coordinates with a huge elevation raster generated some imprecise elevation ranges, so I would suggest users use values taken directly from GBIF occurrences if working with montane species over large geographic areas.
Thanks again for this great package.
You can close the argument.

**Comment by gdauby** [comment]
Hello, thanks for your comment.
Yes, AOH.estimation function should take as inputs either spatraster of sf polygons or both to clip EOO, but the function is still experimental and probably bugging. I shall work on it soon.

I assume you used a sf polygon within the EOO.computing function.

**Comment by gdauby** [comment]
Issue closed for the moment, but will re open if a better way to do it with AOO.estimation
