### ISSUE TITLE
Trouble using a protected areas shapefile

### ISSUE THREAD

**Issue by amcilwee** [gdauby/ConR#6]
Hi, I'd like to run IUCN.eval on fauna and flora species in New South Wales (Australia). I want to create maps and look at the status of species post the 2019-2020 bushfire season, so I am substituting a RFS fire extent map for National Park boundaries. The problem I have, is that no matter what shapefile I include - I get an error "Error in { : task 1 failed - "need finite 'ylim' values" when creating png maps, and "Error in { : task 1 failed - "figure margins too large" when creating pdf maps. 

This only seems to happen when the script hits a species that has records inside the fire-affected area.

I have attached a test file (frog records) and associated shapefiles. The settings I've applied are:

Results <- IUCN.eval(MyData,
          country_map = NSW_NPWS_Branch,
          Cell_size_AOO = 2,
          Cell_size_locations = 10, 
          SubPop=TRUE,
          Resol_sub_pop = 5,
          method_locations = "fixed_grid",
          Rel_cell_size = 0.05, 
          DrawMap = TRUE,
          add.legend = TRUE,
          file_name = NULL,
          export_shp = TRUE,
          write_shp = TRUE, 
          write_results=TRUE,
          map_pdf = TRUE,
          draw.poly.EOO=TRUE,
          exclude.area = TRUE,
          method_protected_area = "other", 
          protec.areas=NSW_RFS_FireExtent,
          ID_shape_PA = "FID_RFSfir", 
          buff_width = 0.1,
          alpha=0.9,
          buff.alpha=0.1, 
          method.range="alpha.hull",
          nbe.rep.rast.AOO=0,
          showWarnings=TRUE,
          write_file_option="csv", 
          parallel=TRUE,
          NbeCores=12)

[NSW_ConR_Test.zip](https://github.com/gdauby/ConR/files/4304736/NSW_ConR_Test.zip)

Cheers, Allen

PS. Is there a way I can change "number of protected areas" on the maps to "number of records in burnt area". In updated versions, it would also be great if a shapefile of the point locations of each species could be automatically generated (in the folder shapesIUCN), along with the EEO and subpop polys.

**Comment by gdauby** [comment]
Hi
I am on the field with limited email access until 26th March.
I try to look at this asap, perhaps before that date.
Best regards
Gilles

**Comment by amcilwee** [comment]
Thanks Gilles. Anytime you get the chance would be great. It’s a fantastic package you’ve developed.

Cheers
Allen

**Comment by amcilwee** [comment]
Hi Gilles, just wondering if you had a chance to look at the test files and resolve the error issue? This would greatly assist me. cheers Allen.

**Comment by gdauby** [comment]
Hi
could you install the development version and test it?
`devtools::install_github("gdauby/ConR")`
Tks

**Comment by gdauby** [comment]
Try:


```
Results <- IUCN.eval(MyData,
country_map = NSW_NPWS_Branch,
Cell_size_AOO = 2,
Cell_size_locations = 10,
SubPop=TRUE,
Resol_sub_pop = 5,
method_locations = "fixed_grid",
Rel_cell_size = 0.05,
DrawMap = TRUE,
add.legend = TRUE,
file_name = NULL,
export_shp = TRUE,
write_shp = TRUE,
write_results=TRUE,
map_pdf = FALSE,
draw.poly.EOO=TRUE,
exclude.area = TRUE,
method_protected_area = "other",
protec.areas=NSW_RFS_FireExtent,
ID_shape_PA = "FID_RFSfir",
buff_width = 0.1,
alpha=0.9,
buff.alpha=0.1,
method.range="alpha.hull",
nbe.rep.rast.AOO=0,
showWarnings=TRUE,
write_file_option="csv",
parallel=TRUE,
NbeCores=4)
```

**Comment by gdauby** [comment]
The new version now on CRAN should be fine.

**Comment by amcilwee** [comment]
Thanks so much for this, will be looking at it today.
