### ISSUE TITLE
develop functions specific to each iucn criterion

### ISSUE THREAD

**Issue by gdauby** [gdauby/ConR#7]
write down specific functions for each criterion
deprecate IUCN.eval function

**Comment by LimaRAF** [comment]
@gdauby function `criterion_A` already usable but need testing. Will finish off `criterion_B` soon.

**Comment by gdauby** [comment]
@LimaRAF added new functions for categorization IUCN for criterion A and B + minor bugs + update namespace

**Comment by LimaRAF** [comment]
@gdauby added the new (but preliminary) function A, C and D. There are many things to do, so we could rather try to organize all tasks inside a project in the repository. So I am closing this issue and opening a project. Let me know what you think.
